### PR TITLE
Updated CLI Docs for appsody list and appsody init changes

### PR DESCRIPTION
**Pull request by kewegner**
1. Updated Environment variables doc with APPSODY_PROJECT_DIR table
2. Updated initialization doc initializing project doc with latest appsody list and appsody init syntax.

@tomleah @Kamran64 I could not get the table to line up column wise in environment-variables.md
Also the output of appsody list correctly formatted on the website, but does not seem to format in the .md below.

Also the build is failing with "YAMLException: duplicated mapping key at line 32, column 5:

          id: nodejs-loopback

          ^"

could it  be it can't tell the difference between:
# Appsody Shell Variables and # Appsody Environment Variables?  

Could you open request revisions and give me some feedback on how to change it?

I tested the output using gatsby develop.

### CODE REVIEW

**Comment by Kamran64** [comment]
Looks good, added a couple of minor changes including a fix for the column width. Still looking into why ```appsody list``` isn't formatting properly in the .md - Although I'm noticing this problem also exists in https://github.com/appsody/website/blob/master/content/docs/stacks/create.md

**Comment by kewegner** [comment]
I made the change re: %nbsp;
I don't think we should mess with the .css, unless someone on the website team makes that change, because of possible downstream effects???

**Comment by tomleah** [comment]
Sorry @kewegner, I didn't mention we put a fix in for the spacing with css in https://github.com/appsody/website/pull/186

So I don't think `&nbsp;` is needed here anymore

**Comment by kewegner** [comment]
@tomleah are there any fixes for the columns spacing issue?  I can remove the &nbsp;

**Comment by kewegner** [comment]
removed the &nbsp;

**Comment by tomleah** [comment]
My thought was the column spacing would be okay to leave @kewegner and let the content determine the spacing here. If others disagree I think we can open a separate issue for it and contain this PR 🙂

**Comment by Kamran64** [comment]
Fine with me, I've set the requested changes to resolved.

**Pull request merged**
