### PR TITLE
added new image to replace appsody flow diagram

### PR DESCRIPTION
**Pull request by KyeMaloy97**
## Checklist

- [x] commit message follows [commit guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).
- [x] website builds and runs in production - for information on how to test locally go [here](https://github.com/appsody/website/blob/master/DEVELOPMENT.md).

## Description
Added a new diagram to show the architecture of Appsody.

## Screenshots
Screenshot 2019-11-27 at 16 28 36

## Related Issues

#322

### CODE REVIEW

**Comment by sympatheticmoose** [comment]
Any thoughts on 'Library' or 'Libraries' @helenmasters ?

**Comment by helenmasters** [comment]
> Any thoughts on 'Library' or 'Libraries' @helenmasters ?

My first thought was as we talk about Appsody stacks and "runtimes, frameworks, and libraries" we should go plural for all or none. However, thinking about it some more... the diagram shows one stack so IF we expect one stack to have multiple libraries, one framework and one runtime then it would make more sense as "libraries".

**Comment by sympatheticmoose** [comment]
> However, thinking about it some more... the diagram shows one stack so IF we expect one stack to have multiple libraries, one framework and one runtime then it would make more sense as "libraries".

I suspect here be dragons.

I can't imagine there would be multiple runtimes, but depending on how you define framework - could be multiple. For example the `nodejs-express` stack, we would typically describe Express as the framework, but that includes the Connect middleware (which is what we use in the `nodejs-functions` stack) - that middleware https://www.npmjs.com/package/connect describes itself as 'extensible HTTP server framework'. It would be common to include multiple libraries.

**Comment by sympatheticmoose** [comment]
[Architecture.ai.zip](https://github.com/appsody/website/files/3947272/Architecture.ai.zip)
Needed this in illustrator format for some video work - figured would attach here just in case useful to others

**Comment by helenmasters** [comment]
Merging as have a verbal thumbs up from David Harris too.

**Pull request merged**
