### PR TITLE
Convert the JAX-RS tutorial

### PR DESCRIPTION
**Pull request by helenmasters**
## Checklist

- [x] commit message follows [commit guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).
- [x] website builds and runs in production - for information on how to test locally go [here](https://github.com/appsody/website/blob/master/DEVELOPMENT.md).

## Description
PR to allow collaboration on updating the JAX-RS tutorial

## Related Issues
#530

### CODE REVIEW

**Comment by helenmasters** [comment]
This draft PR will require:

- The What is Appsody? section probably needs a rewrite (as we shouldn't need as much of this information now it's hosted on the Appsody website)
- If the Appsody logo is included this link needs fixing to reference a local version
- Within Next Steps the link out to the tutorials on medium will need to reference the tutorials on appsody.dev

**Comment by scottkurz** [comment]
We're going to use the java-openliberty stack for this right?

**Comment by helenmasters** [comment]
> We're going to use the java-openliberty stack for this right? (I see it's just a draft now).

Yes Scott, I've opened this as a draft PR so that Adam can make the updates (as he very kindly offered :-)).

**Comment by helenmasters** [comment]
@scottkurz and @awisniew90 I've made you both reviewers but only one of you needs to do a review. So whichever of you has a few minutes please can you do a final review on this tutorial, as I think it's now ready to be merged.

**Comment by SueChaplain** [comment]
@neeraj-laad - Adam has approved the tutorial, but it's still showing review-required. Perhaps you can take one final look and review/approve/merge. Thanks

**Pull request merged**
